### PR TITLE
Differentiated the Corvette and Firebird a bit more by @Pointedstick

### PR DESCRIPTION
**Pull request by MCOfficer**
Ref: endless-sky/endless-sky#3411

> This PR differentiates the Corvette and Firebird from one another, as right now they are very similar (see endless-sky/endless-sky#1626). Changes:
> ## Corvette
> 
>  * Increased shields, gave it a more powerful shield generator, and reduced hull, to better match its price and the description ("experimental lightweight materials", "its weak hull is more than compensated for by its advanced shielding matrix")
> 
> 
> ## Firebird
> 
>  * Increased hull and reduced shields to better match the description ("long and storied past", "basic design remains almost the same", "rugged ship and easy to repair")
> 
>  * Changed default armament to better match the galactic North region of space that its company Betelguese Shipyards comes from; Particle Cannons replace the Heavy Lasers

### CODE REVIEW

**Comment by Amazinite** [comment]
Labeled considering because it's a balance change.

**Comment by Amazinite** [comment]
Well I’m afraid I can’t edit this PR because the branch owner (you) wasn’t actually the one to request it. :)

**Comment by Pointedstick** [comment]
Then I guess @MCOfficer can :stuck_out_tongue:

**Comment by Amazinite** [comment]
I don’t believe so. I think you’d need to give permission for either of us to edit. On desktop view, is there a checkbox on the right side under the PR participators that says “give maintainers access” or something like that? If you check that we could edit.

**Comment by jafdy** [comment]
PR the PR then he could just merge it?

**Comment by Amazinite** [comment]
Merged manually via e618181

**Pull request closed without merging**
