### PR TITLE
added a "prudent" personality for #3383 by @KiLEdEnNis

### PR DESCRIPTION
**Pull request by MCOfficer**
Ref: endless-sky/endless-sky#3441

> so with a lot of blood, sweat, confusion, dumb errors and a lot of patience from @tehhowch & @Hadron1776 who helped me a LOT (teaching/reviewing/pointing out idiocy) I managed to add the "prudent" personality (from endless-sky/endless-sky#3383)
> 
> what it does:
> ships with the prudent personality will only deploy fighters/drones under the exact same circumstances as frugal ships would use missiles:
> when the ship lost 50% hull or shield, or when the ship and its allies are outgunned
> 
> in other words:
> ships with the prudent personality will only launch their fighters/drones if they are outgunned or they lost a significant portion of their health
> 
> I still don't exactly understand everything but I have some minor C# knowledge which isn't that different, so I'll be able to edit it based on feedback
> 
> & again big thanks to Tehhowch & Hadron* (no idea why I thought it was Comnom, Hadron was the one that said "define that bool", oops), 0 chance I could have done this without them

### CODE REVIEW

**Comment by Amazinite** [comment]
Labeled considering because of this being a first time code PR from Kile. Not doubting his abilities, just want this double checked first to make sure everything is a-okay, cus it looks like some commits were made without anyone commenting on them.

**Comment by Lorantine** [comment]
> Not doubting his abilities

You should. I barely started IT college at the time, and it didn't include the C++ language, so I had no clue what I did and had two others do almost all the work.

**Comment by Amazinite** [comment]
Well I've been dealing with the source code lately, so I'm hoping to get this functionality added to the master for v0.9.11. I'll love over your code and make any fixes if necessary. 👍

**Comment by Lorantine** [comment]
Do as you wish, and good luck.

**Pull request closed without merging**
