### PR TITLE
Fighter Overhaul

### PR DESCRIPTION
**Pull request by Startome**
Hyratel and I feel that the current system for the use of fighters and drones is unbalanced, and has led to many players abandoning the idea of using them altogether. 

When the NPC ships spawn with a full complement, players often find fighters to be very interesting. But when they try to use them, find that they die very quickly in a battle, and that a standard warship would have been a better choice than a fighter.

Also the need to spend money to replace them, where a standard warship never would have died in the first place, is also quite a deterrent.

The need to spend money to replenish them, and the fact they often die before doing any damage in a large battle, essentially rules them out as a combat effective option. A Captured capital ship makes a much better meat shield.

Especially considering that most players customize their ships, including fighters. The loss of a single fighter can take quite some time to replace, and they are often lost far faster than they can be rebuilt.
So we propose adjusting the fighter system to be more appealing to the player, and more practical, without breaking the game’s balance.  This being to expand interest, and most importantly, strategies available.

I know this idea has been suggested in the past, however only as a quick request for some kind of solution. Not that I have read, has a concrete proposal been brought forth.

The most important part of our proposal is to add a module that allows carrier ships to gradually, at high energy and heat cost (and perhaps resources, depending on the ease of coding and balance), to regenerate their fighters both during and after battles. This module would take up a substantial amount of space. The outfit space, combined with the energy and heat demands, would provide the player with two options:

Only equip one manufacturing module, greatly reducing the rate at which the carrier could deploy its fighters, while maintaining weapons. Effectively serving a multirole purpose.

Focus on fighters, allowing the carrier to field fighters at a slightly less tedious rate, but requiring it to serve a true support role, as carriers traditionally do.

We believe a balanced starting point with the numbers would be for the module to occupy 50 general outfit space, while consuming 500 energy and generating 650 heat. This seems fairly realistic for a manufacturing facility, and balances the demands on the player. Meaning early game they have to make sacrifices, as they do with all builds. And late game, as more efficient alien generators, shield mods, etc, are unlocked, they can truly optimize their ships to be the most effective.

The manufacturing module could produce 2 mass per second. This would allow current fighter models to be redeployed (after the initial bay occupant is destroyed in battle) after 52-74 seconds, depending on which fighter. (the boxwing would be lowest, but isn’t truly a combat unit, so is not included)
Current drones would be redeployed at 34-59 seconds, depending on the model.

This module would not drastically affect the balance of any one battle, though the slight changes it would cause seem to be more practical, and more appealing to the player. However it would make even bothering to maintain fighters in one’s navy far more appealing.

Now this idea would be much more appealing if it required the least coding modification possible. As such, one idea would be that in the shipyard where one would normally purchase a fighter, there is a second option for each fighter, one that functions like a “Blueprint” of sorts, which the manufacturing module would reproduce. Obviously this would be noticeably higher in cost than that of its single use fighter. 

The Manufacturing module would follow the same concept as shield regenerators and hull repair. When a fleet lands, they function to the maximum effect and completely restore the ship. (if a ship has a hull repair module on board, even on an uninhabited planet, when you land it fully restores) 

I did receive a suggestion from comnom that the fighter/drone could be cached when destroyed instead of being removed.
The next obstacle is how to handle the replacement crew for the fighter, as the original pilot died when it was destroyed.
The aim would be to have the game AI replace fighters in the order in which they were destroyed, and auto deploy them if the player hasn’t issued a command to land since the previous deploy command.

We also believe, should this module be implemented, that the players would want new fighters and drones to increase the available strategies. This would help to encourage content creators to add additional fighters and fitting modules as well.

### CODE REVIEW

**Comment by TheMarksman-ES** [comment]
Another idea put forth is to have fighter weapons that make fighters capital ship killers.
The only thing preventing them from being OP would be to have ammo limits(Very high ammo limits) or debuffs to the ship.

**Comment by PierceGepard** [comment]
Definitely love the idea since it reminds me of Star Sonata 2's fighters (viable and fun to have fighters)
Maybe being able to store some fighters/drones as a backup?
Have some ready to launch fighters/drones for when you lose any that is already out in battle?
Ideas coming to me from Star Sonata 2.

**Comment by Zitchas** [comment]
I really like the idea of having the capacity to manufacture replacement fighters and drones. That'd definitely make flying a support ship an interesting idea for some of the annoying FW battles.

**Comment by jafdy** [comment]
Quick question: Why is this a PR?

**Comment by MCOfficer** [comment]
it's a WIP, and all the current changes slipped over from the ES master (time to update the community fork).

**Comment by jafdy** [comment]
No no, this isn't trying to merge anything it sounds more like an issue.

**Comment by MCOfficer** [comment]
well, that was not intentional... I was just updating from the ES master. well, not like anything substantially was lost, and as jafdy said it would've been better suited as issue (at least until there are actual changes).

**Comment by Startome** [comment]
XD I usually leave github to those more code inclined.  I'll try to properly add it as an issue next time.

**Comment by PierceGepard** [comment]
http://wiki2.starsonata.com/index.php/Fighters
If you want to look at how SS2 does fighters, here it is.
I'm not sure about making something like Tech levels/tiers tho.

( Star Sonata 2 basically feels like its a mediocre MMO ES )
( try it if you wish. it's relatively entertaining )

**Comment by Startome** [comment]
I would love to see someone with the appropriate coding experience take to this idea and help. Anyone interested, or have an adjustments they recommend?

**Pull request merged**
