### PR TITLE
Fighters now rearm on the carrier when launching by @zwparchan

### PR DESCRIPTION
**Pull request by MCOfficer**
Ref: endless-sky/endless-sky#1971

>This allows fighters to rearm missiles from the carriers cargo hold. This is one of the changes being considered for endless-sky/endless-sky#1939.
>The only real rough edge I've seen is that landing on a planet without an outfitter does not rearm your fighters, but I haven't tested much.

### CODE REVIEW

**Comment by tehhowch** [comment]
Why this and not https://github.com/endless-sky/endless-sky/pull/3791?

**Comment by MCOfficer** [comment]
i didn't go through your PRs yet, so i missed it. you're right, this should be close once 3791 is PR'd here.

**Comment by Amazinite** [comment]
@tehhowch go ahead and PR to the community branch of this fork any of your open PRs to the ES main branch. This PR was just on my list of “maybes,” and since I’m not someone that deals with the game code, I only looked at the intended functionality of code PRs and not whether they’re actually good implementations.

**Comment by Amazinite** [comment]
Labeled considering due to Tehhowch's PR superseding this one. I'll close this PR if Tehhowch's gets PRed here.

**Pull request closed without merging**
