### PR TITLE
Brig and prisoner transport jobs by @Pointedstick

### PR DESCRIPTION
**Pull request by MCOfficer**
Ref: endless-sky/endless-sky#3347

> I've added a new style of job: in-person bounty hunting/prisoner transportation. These jobs are unlocked by owning a new outfit: the Brig, available on Pirate worlds and throughout the Galactic South.
> 
> brig
> 
> Pirate slavery jobs also now require a Brig.
> 
> The Brig contrasts with [Luxury Accommodations](https://github.com/endless-sky/endless-sky/pull/3359) and unlocks a completely different kind of job: transporting wanted criminals, in-person bounty hunting, apprehending fleeing fugitives, and so on. The point is to encourage players to choose what kind of captain they really are. Will you be a scoundrel who profits from human misery and lives dangerously? Will you cater to rich elitists instead? Or will you play it safe and stick to more normal jobs?
> 
> Why? endless-sky [once said:](https://github.com/endless-sky/endless-sky/issues/1070#issuecomment-219245709)
> 
> > The only reason to add new features that make the game more complicated is if they would make the player's behavior more varied or interesting.
> 
> I think this counts. It's a soft role-playing opportunity; a way for players to flesh out their captain's personality. By purchasing a Brig, players are simultaneously forced to confront something about their own behavior, and also rewarded for it by unlocking new game content--at a potential cost to their humanity...
> 
> Errata: the boarding missions do work properly, but are affected by endless-sky/endless-sky#3129.
> 
> I would have added much more bounty hunting content, but was stymied by the lack of endless-sky/endless-sky#3340, endless-sky/endless-sky#1763 and endless-sky/endless-sky#3129.

### CODE REVIEW

**Comment by Pointedstick** [comment]
Woohoo! Now how about luxury accommodations? https://github.com/endless-sky/endless-sky/pull/3359

**Comment by Pointedstick** [comment]
Should I be submitting future PRs here instead of the original repo? Is the original ES dead and this is a community-supported fork?

**Comment by MCOfficer** [comment]
For the time being, this is merely a "playground" for the community, where we can experiment with unmerged features. It doesn't attempt to replace or even be of the same importance as the official repo. Threrefor, PRs should be made to the official repo, and may optionally be duplicated here.

**Comment by Pointedstick** [comment]
Ok, thanks for the clarification!

Any word on what's, uh, happening with respect to the main repo and its developer?

**Comment by Amazinite** [comment]
No idea. No response on endless-sky#3958, which was only created because Kiko wasn't getting a response from his email to MZ. Last commit was over a month ago, but no word on the conclusion of the Wanderer campaign, which is suppose to be part of v0.9.9. Word is that MZ is alive, but probably either just not in the mood for working on ES or he's been working on something big that's taking a while. 

Given that the last release (v0.9.8) was over a year ago now, let's just say that there are a few people we've had expressing sentiment of wanting to jump ship. I'm certainly still keeping my eye on things, but I myself haven't had much motivation to create new content for the game due to the lack of updates and the lack of interaction with open PRs (the latter of which is mainly why this fork exists). e.g. endless-sky#3120 is over a year old now. It may be marked for v0.9.x, but there's not even a sign of another v0.9.x release on the horizon.

**Pull request merged**
